version: '3.8'

services:
  web:
    image: nginx
    ports:
      - "${APP_PORT}:80"
    environment:
      - ENV=${APP_ENV}
    
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
